version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_username
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: your_database_name
    volumes:
      - ./:/var/www/html

