name: WordPress
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install WordPress
        run: |
          docker pull wordpress:latest
          docker run -it -p 9000:80 wordpress:latest
      - name: Call route
        run: |
          curl http://localhost:80/another-route
          if [ $? -ne 0 ]; then
            echo "Call to another route failed"
            exit 1
          fi
